package hackathon.server.exception;

public class AlreadyMatchedUserAndProduct extends RuntimeException{
}
